import type { Metadata } from "next";
import Link from 'next/link';
import "../app/globals.css";
import React from "react";
import type { ReactNode } from 'react';

export const metadata: Metadata = {
  title: "M.Fk Shopping Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        
        
        <main>{children}</main>
        
        
      </body>
    </html>
  );
}





